### PR TITLE
UserActivityListener: user activity listener no longer waits for play…

### PR DESCRIPTION
**Pull request by will-p-github-zz**
… and built

## Description
Please describe the change as necessary.
If it's a feature or enhancement please be as detailed as possible.
If it's a bug fix, please link the issue that it fixes or describe the bug in as much detail.

## Specific Changes proposed
Please list the specific changes involved in this pull request.

## Requirements Checklist
- [ ] Feature implemented / Bug fixed
- [ ] If necessary, more likely in a feature request than a bug fix
  - [ ] Change has been verified in an actual browser (Chome, Firefox, IE)
  - [ ] Unit Tests updated or fixed
  - [ ] Docs/guides updated
  - [ ] Example created ([starter template on JSBin](https://codepen.io/gkatsev/pen/GwZegv?editors=1000#0))
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

**Comment by ethanmills** [comment]
Just for future reference, this is in relation to VCP-1279. We want VideoJs to report on user activity from as soon as it initialised, instead of the start of playback.

**Review by ethanmills — APPROVED** [review]
Looks good!

**Review by ethanmills — CHANGES_REQUESTED** [review]
Looks good! Could you stick it on a different branch for a 7.5.6 so we can track the change though please? You will then need to update the branch we pull from in the core's package.json

**Review by benswannack — APPROVED** [review]
Looks good!

**Comment by ethanmills** [comment]
Replaced by #8

**Review by ben-fernandes-sw — COMMENTED** [review]
👍

**Pull request closed without merging**
